create table if not exists team (
	id integer generated by default as identity,
	city varchar(30) not null,
	team_name varchar(30) not null,
	primary key (id));

create table if not exists game (
	id integer generated by default as identity, 
	line double not null, 
	over_under double not null, 
	start_date_time timestamp not null, 
	week_number integer not null, 
	favorite_team_id integer not null, 
	home_team_id integer not null, 
	visiting_team_id integer not null, 
	primary key (id));